### ISSUE TITLE
Not able to make this theme work on github

### ISSUE THREAD

**Issue by pathakraul** [brijeshb42/bitwiser-material#1]
Hi Brijesh,

I am trying to use your theme and cannot make this theme work properly. I pushed your gh-page branch on my github pages repo without making any changes and it does not render properly. This is the url: https://rahulpathakml.github.io.   
![screenshot from 2016-11-08 12-41-46](https://cloud.githubusercontent.com/assets/23165276/20090054/c9cc5134-a5b0-11e6-9286-77aa276f39eb.png)

PS: It works fine if I locally use "jekyll serve" and open on localhost

**Comment by brijeshb42** [comment]
Value for `url` in `_config.yml` should be your own url - `https://rahulpathakml.github.io`. You should also change other values in that file. It is currently using my own defaults.

**Comment by pathakraul** [comment]
Yes, Thanks for that. Its working now.
